project:
  type: website
  output-dir: docs

website:
  title: "Kyle Haynes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: blah.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

